# Generated by Django 3.1.2 on 2020-10-02 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('MUSIC', 'Music'), ('YOUTUBE', 'YouTube'), ('QUOTE', 'Quote')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
