# Generated by Django 3.1.2 on 2020-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201002_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
